---
- name: Installing andrewrothstein.temurin (jdk)
  ansible.builtin.include_role:
    name: andrewrothstein.temurin
  vars:
    temurin_app: jdk
- name: Installing andrewrothstein.temurin (jre)
  ansible.builtin.include_role:
    name: andrewrothstein.temurin
  vars:
    temurin_app: jre
- name: Check for installation in {{ teamcity_install_versioned_dir }}
  become: true
  ansible.builtin.stat:
    path: '{{ teamcity_install_versioned_dir }}'
  changed_when: false
  register: teamcity_binary
- name: Downloading and installing TeamCity
  when: not teamcity_binary.stat.exists
  block:
    - name: Downloading {{ teamcity_tgz_url }} to {{ teamcity_tmp_tgz }}
      become: true
      become_user: root
      ansible.builtin.get_url:
        url: '{{ teamcity_tgz_url }}'
        dest: '{{ teamcity_tmp_tgz }}'
        mode: '644'

    - name: Mkdir {{ teamcity_install_versioned_dir }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ teamcity_install_versioned_dir }}'
        state: directory
        mode: '755'

    - name: Unarchiving {{ teamcity_tmp_tgz }} to {{ teamcity_install_versioned_dir }}
      become: true
      become_user: root
      ansible.builtin.unarchive:
        remote_src: true
        src: '{{ teamcity_tmp_tgz }}'
        dest: '{{ teamcity_install_versioned_dir }}'
        creates: '{{ teamcity_install_dir }}'
  always:
    - name: Rm {{ teamcity_tmp_tgz }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ teamcity_tmp_tgz }}'
        state: absent

- name: Linking {{ teamcity_link_dir }} to {{ teamcity_install_dir }}
  become: true
  become_user: root
  ansible.builtin.file:
    src: '{{ teamcity_install_dir }}'
    dest: '{{ teamcity_link_dir }}'
    state: link

- name: Add to login shell path...
  become: true
  become_user: root
  with_items:
    - f: TeamCity.sh
      d: /etc/profile.d
  ansible.builtin.template:
    src: '{{ item.f }}.j2'
    dest: '{{ item.d }}/{{ item.f }}'
    mode: '{{ item.m | default("644") }}'
